name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATEKEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 5.9.51.83 >> ~/.ssh/known_hosts
        env:
          PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
        
      - name: Pull code
        run: |
          ssh root@5.9.51.83 "cd /var/www/backend && git stash && git pull origin master && npm install && pm2 restart all"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
